server:
  port: @server.port@
management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false
spring:
  application:
    name: @project.name@
  output:
    ansi:
      enabled: always
info:
  version: @project.version@
  stage: dev

kafka:
  bootstrap.servers: "localhost:29092"
  topic:
    webhook:
      forward: webhook-forward
      first.retry: webhook-first-retry
      second.retry: webhook-second-retry
      third.retry: webhook-third-retry
      last.retry: webhook-last-retry
      dead.letter.queue: webhook-dead-letter-queue
  ssl:
    enable: false
    keystore-location: src/main/resources/cert/kenny-k.struzhkin.p12
    keystore-password: kenny
    key-password: kenny
    server-password: kenny12
    server-keystore-location: src/

merchant:
  callback:
    timeout: 10

retry:
  first.seconds: 30
  second.seconds: 600
  third.seconds: 1800
  last.seconds: 6400
  dead.time.hours: 24